#!/usr/bin/python
#TODO - [put hashrates, miner, OC settings in cfg file for each GPU.-DONE] Default to GPU0?
#TODO - encompass xinit display in this script
#TODO - error handling (internal and external)
#TODO - verify hashrate with api
#TODO - add power limits to config file
#TODO - move miner command list to config file
#TODO - implement OC commands
#TODO - tie gpu uuid to hashrates
#TODO - create xorg scripts tied to pci address
#TODO - root access for persistence mode and creating xorg scripts?


import shlex, subprocess, time, psutil, datetime, json, urllib, sys, os, signal, socket, re


def miner_cmd(gpu, miner, algo, location, port, username, minerid, password, intensity):
    cmd=""
    if miner=="ccminer-tpruvot" or miner=="ccminer-klaust" or miner=="ccminer-alexis78":
	if intensity<0: intensity=""
	else: intensity="-i "+str(intensity)
	cmd="-a "+algo+" --url=stratum+tcp://"+algo+"."+location+".nicehash.com:"+port+"#xnsub --userpass="+username+"."+minerid+":"+password+" "+intensity #+" -d "+str(gpu)
    elif miner=="cgminer":
	if intensity<0: intensity=""
	else: intensity="-i "+str(intensity)
	cmd="-a "+algo+" --url=stratum+tcp://"+algo+"."+location+".nicehash.com:"+port+"#xnsub --userpass="+username+"."+minerid+":"+password+" "+intensity
    elif miner=="nheqminer": #nheqminer won't connect anymore
	cmd="-l "+algo+"."+location+".nicehash.com:"+port+" -u "+username+"."+minerid+" -p "+password
    elif miner=="EWBF":
	if intensity<0: intensity=""
	else: intensity="--intensity "+str(intensity)
	cmd = "--server "+algo+"."+location+".nicehash.com --port "+port+" --user "+username+"."+minerid+" --pass "+password+" --fee 0 --templimit 75 --pec --eexit 1 "+intensity #+" --cuda_devices "+str(gpu)
    return cmd

algos = []
miner = []
best_algo = 0
gpucount = 0
rate = 0
devnull=open(os.devnull, 'wb')
rundir = os.path.dirname(os.path.realpath(sys.argv[0]))



class Algo:
    def __init__(self, number, name, paying, port, hashrate, miner, intensity, coreclock, memclock):
	self.nh_name = name
	self.nh_paying = paying
	self.nh_number = number
	self.nh_port = port
	self.hashrate = hashrate
	self.miner_name = miner
	self.ratio = float(paying) * float(hashrate)
	self.intensity = intensity
	self.coreclock = coreclock
	self.memclock = memclock

class Miner:
    def __init__(self, name, path, prog):
	self.name = name
	self.path = path
	self.prog = prog

def init():
    global miner
    execfile(rundir+"/tuffmine.cfg", globals())
    for line in minerprog:
        miner.append(Miner(line[0], line[1], line[2]))

def updatealgos():
    global algos, best_algo, rate, ts
    #Check config for any setting updates
    execfile(rundir+"/tuffmine.cfg", globals())
    #Find USD/BTC rate
    rate=json.load(urllib.urlopen(btcurl))["amount"]
    ts=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print("***** "+ts+" USD/BTC: "+rate+" (Coinbase) *****")

    data=json.load(urllib.urlopen(algourl))
    data = data['result']['simplemultialgo']
    for gpu in range(gpucount):
	tempalgos = [None]*len(data)
	for line in data:
	    hashdata=hashlookup(gpu, line["name"])
	    tempalgos[line["algo"]] = (Algo(line["algo"],line["name"],line["paying"],line["port"],hashdata[0],line["name"],hashdata[2],hashdata[3],hashdata[4]))

	#Sort the algorithms in ascending profit
	tempalgos=sorted(tempalgos, key=lambda tempalgos: tempalgos.ratio)

	#Display profitability of each active algorithm
	header="{:<16}".format("GPU"+str(gpu)+" Algo")+": "+"{:<8}".format("mBTC/day")+" : "+"{:<8}".format("USD/day")
	print(header)
        for algo in tempalgos:
	    if algo.ratio > 0:
    		algotxt="{:<16}".format(algo.nh_name)+": "+"{:<8}".format(str(algo.ratio)[:7])+" : "+str(format(algo.ratio*float(rate)/1000, '.2f'))
		print(algotxt)
	best_algo[gpu] = len(tempalgos)-1
	algos[gpu]=tempalgos


def checkGPU():
    global gpucount, algos, best_algo


    gpu_list=runcmd("nvidia-smi --query-gpu=index,pci.bus_id,uuid,name --format=csv,noheader")
    matches = re.findall(
	r"(?P<idx>\d*), (?P<pci>.*), (?P<uuid>.*), (?P<name>.*)",
	gpu_list
    )
    gpucount=len(matches)
#    print("Found "+str(gpucount)+" cards")
    if gpucount==0:
	print("No NVIDIA cards found, exiting")
	sys.exit(1)
    else:
	print("NVIDIA cards found: "+str(gpucount))
	for card in matches:
    	    #print(gpu_list)
            gpu_idx=int(card[0])
            pci=card[1]
            uuid=card[2]
            name=card[3]
		#pci=runcmd("nvidia-smi --query-gpu=pci.bus_id --format=csv,noheader -i "+str(card))
            domain=int(pci.split(":")[0],16)
            bus=int(pci.split(":")[1],16)
            device=int(pci.split(":")[2].split(".")[0],16)
            function=int(pci.split(":")[2].split(".")[0],16)
            address=str(bus)+"@"+str(domain)+":"+str(device)+":"+str(function)
            #bus@domain:device:function
            print("GPU "+str(gpu_idx)+": "+address+" and uuid="+uuid+" ("+name+")")
	algos = [None]*gpucount
	best_algo = [0]*gpucount


#    gpus_info=runcmd("nvidia-smi -L")
#    matches = re.findall(
#	r"GPU (?P<gpunum>\d*):.*GPU-(?P<uuid>\w{8}-\w{4}-\w{4}-\w{4}-\w{12})",
#	gpus_info
#    )
#    cards = None if not matches else {gpunum: "GPU-"+uuid for gpunum, uuid in matches}

#    if cards is None:
#	print("No NVIDIA cards found, exiting")
#	sys.exit(1)

#    else:
#	gpucount=len(cards)
#	for card in range(gpucount):
#	    pci=runcmd("nvidia-smi --query-gpu=pci.bus_id --format=csv,noheader -i "+str(card))
#	    domain=int(pci.split(":")[0],16)
#	    bus=int(pci.split(":")[1],16)
#	    device=int(pci.split(":")[2].split(".")[0],16)
#	    function=int(pci.split(":")[2].split(".")[0],16)
#	    address=str(bus)+"@"+str(domain)+":"+str(device)+":"+str(function)
#	    #bus@domain:device:function
#	    print("GPU "+str(card)+": "+cards[str(card)]+" at PCI address: "+address)
#	    pass
#	    #print("GPU "+str(card)+": "+cards[str(card)])
#	print("NVIDIA cards found: "+str(gpucount))
#	algos = [None]*gpucount
#	best_algo = [0]*gpucount


#    numberofcards=len(cards)
#    for card in range(len(cards)):
#	pass


    #Find number of NVIDIA GPUs:
#    gpucountcmd = "nvidia-smi --query-gpu=count --format=csv,noheader | tail -n 1"
#    gpucount = int(runcmd(gpucountcmd))
#    if gpucount < 1:
#	print("No NVIDIA cards found")
#	sys.exit(1)


def hashlookup(gpu, hashname):
    if hashrates[gpu].has_key(hashname): return hashrates[gpu][hashname]
    else: return 0

def runcmd(stringcmd):
    #cmdrun = subprocess.Popen(shlex.split(stringcmd), stdout=subprocess.PIPE, stderr=devnull)
    cmdrun = subprocess.Popen(stringcmd, stdout=subprocess.PIPE, stderr=devnull, shell=True)
    return cmdrun.stdout.read()

def isInt(mystring):
    try:
	int(mystring)
	return True
    except ValueError:
	return False

def miningpid(i):
    return runcmd("ps ax |grep "+userid+" | grep GPU"+str(i)+" | grep -v 'grep\|SCREEN' |tail -n1 |awk '{print $1}'")

def updateGPUs():
    for gpu in range(gpucount):
	print("")
	minerpid=miningpid(gpu)
	if isInt(minerpid):
	    #Existing miner found.  If using the best algo, do nothing.  Else kill miner and start new
	    minercmd=runcmd("ps -o command= "+str(minerpid))
	    old_algo = 0
    	    for idx, algo in enumerate(algos[gpu]):
		if (algo.nh_name in minercmd) and (str(algo.nh_port) in minercmd):
		    old_algo = idx
		    break

	    if old_algo==best_algo[gpu]:
		print("GPU"+str(gpu)+": "+algos[gpu][old_algo].nh_name)+" already most profitable, no change"
	    else:
		#check if algo delta is large enough to swap
		if algos[gpu][old_algo].ratio == 0:
		    print("GPU"+str(gpu)+": Changing from "+algos[gpu][old_algo].nh_name+" to "+algos[gpu][best_algo[gpu]].nh_name)
		    killminer(gpu)
		    startminer(gpu, best_algo[gpu])
		else:
		    profit_diff = round(((algos[gpu][best_algo[gpu]].ratio / algos[gpu][old_algo].ratio)*100-100),1)
		    if algos[gpu][best_algo[gpu]].ratio > (algos[gpu][old_algo].ratio * (100 + rate_thresh) / 100 ):
			print("GPU"+str(gpu)+": Changing from "+algos[gpu][old_algo].nh_name+" to "+algos[gpu][best_algo[gpu]].nh_name)
			killminer(gpu)
			startminer(gpu, best_algo[gpu])
		    else:
			print("GPU"+str(gpu)+": "+algos[gpu][best_algo[gpu]].nh_name+" "+str(profit_diff)+"% more profitable than "+algos[gpu][old_algo].nh_name+" (switch at "+str(rate_thresh)+"%)" )
	else:
	    #No miner found, start a new one
	    print("GPU"+str(gpu)+": Miner not running")
	    startminer(gpu, best_algo[gpu])


def startminer(gpu, algo):
    #apply overclock
    applyOC(gpu, algos[gpu][algo].coreclock, algos[gpu][algo].memclock)
    location="usa"
    msel = [x for x in miner if x.name==hashrates[gpu][algos[gpu][algo].nh_name][1]][0]
    options = miner_cmd(gpu, msel.name, algos[gpu][algo].nh_name, location, str(algos[gpu][algo].nh_port), userid, socket.gethostname()+"GPU"+str(gpu), password, algos[gpu][algo].intensity)
    cmd="CUDA_VISIBLE_DEVICES="+str(gpu)+" screen -dmS GPU"+str(gpu)+" "+msel.path+msel.prog+" "+options
    print(cmd)
    runcmd(cmd)

def killminer(gpu):
    #remove overclock
    removeOC(gpu)
    print("Killing miner for GPU"+str(gpu)+", pid: "+miningpid(gpu))
    while isInt(miningpid(gpu)):
	os.kill(int(miningpid(gpu)), signal.SIGKILL)
	time.sleep(.5)

def applyOC(gpu, coreclock, memclock):
    pass
    #print("Applying OC")
    #clock=100
    #memory=500
    #runcmd("DISPLAY=:"+str(gpu)+" nvidia-settings -a [gpu:0]/GPUGraphicsClockOffset[3]="+str(clock)+" -a [gpu:0]/GPUMemoryTransferRateOffset[3]="+str(memory)+"")

def removeOC(gpu):
    pass
    #print("Removing OC")
    #runcmd("DISPLAY=:"+str(gpu)+" nvidia-settings -a [gpu:0]/GPUGraphicsClockOffset[3]=0 -a [gpu:0]/GPUMemoryTransferRateOffset[3]=0")

init()
checkGPU()
while True:
    updatealgos()
    updateGPUs()
    sys.exit(0)
    time.sleep(60*updaterate)


